####################
# Snippet generated by PowerShell to store Terraform states on Azure Storage
####################
terraform {
	backend "azurerm" {
		resource_group_name = "XmasDev"
		storage_account_name = "xmasdev71129stg"
		container_name = "terraformstate"
		key = "terraform.tfstate"
	}
}

